#!/bin/bash

## Description: Install Overture Local Project
## Usage: install
## Example: "ddev install"

YELLOW='\033[1;33m'
GREEN='\033[1;32m'
BLUE='\033[1;34m'
RESET_COLOR='\033[0m'

printf "➜ Working in: ${YELLOW}${PWD}${RESET_COLOR}\n"

# Check env file
printf "\n➜ Running: ${YELLOW}Check default env file${RESET_COLOR}\n";
# Add default local .env file.
if ! [[ -f ".env" ]] ; then
    cp .env.example .env \
    && cd storage/ \
    && mkdir -p framework/sessions framework/views framework/cache \
    && chmod -R 775 framework \
    && cd ../
fi

# Run composer install.
printf "\n➜ Running: ${YELLOW}composer install${RESET_COLOR}\n";
ddev composer install

# Generate keys.
printf "\n➜ Running: ${YELLOW}Generate keys${RESET_COLOR}\n";
ddev artisan key:generate

# db:migrate.
printf "\n➜ Running: ${YELLOW}DB:Migrate${RESET_COLOR}\n";
ddev artisan migrate

# db:seed.
printf "\n➜ Running: ${YELLOW}DB:Seed${RESET_COLOR}\n";
ddev artisan db:seed

# We are done.
printf "${GREEN}All done!${RESET_COLOR}\n";
